AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  leiaHook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::562948771536:role/service-role/leiaHook-role-bb870iow'
      Environment:
        Variables:
          ACCOUNT_NAME: hiringcoders3
          ENVIRONMENT: vtexcommercestable
          VTEX_API_KEY: vtexappkey-hiringcoders3-RVRHFM
          VTEX_API_TOKEN: >-
            CUDFEDIHTZMEGEVJDCOZYHLYTVICPIRRZJVEZYPXVCPKIRWMRUUCGUMVIELIUFSLIVFWIRKENRDVRAQBYWLVNPLFWAVUNGCPKDCNMZEAJPPPQRDHOKJYUXYSKAAHWQRG
